apiVersion: v1
kind: Secret
metadata:
  name: tasklist-secrets
  namespace: tasklist
type: Opaque
stringData:
  DB_USERNAME: tasklist_user
  DB_PASSWORD: password
  APPD_CONTROLLER_HOST: "theater202601042150029.saas.appdynamics.com"
  APPD_ACCOUNT_NAME: "theater202601042150029"
  APPD_ACCESS_KEY: "x5nmpxeaod5g"